Repository srivatsamarichi/weather-app, pull requests merged in 2020-04, with the labels that each got.

#1 App Center SDK integration
  README.md
  Weather/WeatherApp.Android/WeatherApp.Android.csproj
  Weather/WeatherApp.iOS/WeatherApp.iOS.csproj
  Weather/WeatherApp/App.xaml.cs
  Weather/WeatherApp/Constants.cs
  Weather/WeatherApp/WeatherApp.csproj
Labels: enhancement

#2 readme updates
  README.md
Labels: documentation

#4 Add a Codacy badge to README.md
  README.md
Labels: documentation, enhancement
